print ("Exercise: ASCII art work")

print (" //   ##   /   /")
print (":###; ;### ;#  ##:")
print (" :### #### ## ##:")
print (":##### #### # ###:")
print (":###### #### ####:")
print (" :##### ### ####:")
print ("  :#### ## ####:")
print ("   :##### ####:")
print ("    :#### ###:")
print ("     &#:#&:#&")
print ("      &&:&:&")
print ("       &&&&")
print ("       ;&&;     /")
print ("        ||    ////")
print ("        ||   /////")
print ("        ||  //////")
print ("        || //////")
print ("        || /////")
print ("        ||////")
print ("        ||//")
print ("        ||/")
print ("        ||")
print ("        ||")
print ("        ||")
print ("        ||")
print ("        ||")
print ("        ||")
print ("        ||")
print ("        ||")
print ("        ||")
print ("        ||")
